sonar.projectKey=ecoaromazone
sonar.projectName=EcoAromazone
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info